### ISSUE TITLE
feature request: a way to copy the final command

### ISSUE THREAD

**Issue by thenbe** [paololazzari/play#1]
What a useful tool this is.

Would you consider adding a way to easily copy the final command, for use elsewhere.

### Solution Ideas:

- The pattern used by [`ijq`](https://github.com/gpanders/ijq) is that it prints the final command to stdout when you're "done".
- A new panel that always shows the full command string so that a user can manually copy it.
- Other

The `ijq` pattern seems like it's simpler.

**Comment by paololazzari** [comment]
Hi @thenbe 

Thank you for opening this issue. I'm glad you like it!

This is a good idea. I plan on making the bindings customizable, but for now, what do you think about `Ctrl+S` ? Feel free to suggest another key binding. You can find the list of available findings [here](https://github.com/gdamore/tcell/blob/main/key.go#L83).

**Comment by thenbe** [comment]
A keybinding is even better than my earlier suggestion as it would enable the user to easily copy the command then, if they wish, continue to further iterate on it in `play`.

**Comment by paololazzari** [comment]
I was thinking that `Ctrl+S` would exit the program printing the whole command to stdout, similarly to how `ijq` does it with `Enter`

**Comment by thenbe** [comment]
I misunderstood then, yeah this would still be very useful. I'm happy with your suggestion, and would also choose it myself for the sake of keeping things simple.

---

If, in the future, someone wants to improve on this I reckon the following would cover most (linux/mac) use cases.

```go
// pseudo code
copy_to_clipboard() {
  if commandExists("xsel")
    echo $COMMAND | xsel --input --clipboard
  elseif commandExists("xclip")
    echo $COMMAND | xclip -selection
  elseif commandExists("pbcopy")
    echo $COMMAND | pbcopy -i
}
```

**Comment by paololazzari** [comment]
This has now been added with the latest commit (v 0.3.1).
